name: test-modified-docstrings
on: [push, pull_request]
jobs:
  run-modified-docstring-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: ivy
          persist-credentials: false
          submodules: "recursive"
          fetch-depth: 2
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Get Git Diff Filelist
        run: |
          cd ivy
          git --no-pager diff "HEAD^..HEAD" --name-only --output name-changed
          python3 dump_diff.py

      - name: Run Docstring Tests
        run: |
          cd ivy
          docker run --rm -i -v "$(pwd)":/ivy unifyai/ivy:latest python3 -m pytest ivy/ivy_tests/test_modified_docstrings.py -s
